### ISSUE TITLE
CUDA problem ：）

### ISSUE THREAD

**Issue by jexz11** [drboog/Lafite#3]
**Training with language-free methods (pseudo image-text feature pairs)**
**My code:**

`python train.py --outdir=D:\\python_learning\\lafite\\Lafite-main\\data\\training-runs  --data=D:\\python_learning\\data\\pokemon数据集\\905all\\256\\white\\dest_train\\train.zip  --test_data=D:\\python_learning\\data\\pokemon数据集\\905all\\256\\white\\dest_test\\test.zip --mixing_prob=1.0 --cfg=auto`

**feedback:**

Constructing networks...
**Setting up PyTorch plugin "bias_act_plugin"... Failed!**

D:\python_learning\lafite\Lafite-main\torch_utils\ops\bias_act.py:43: UserWarning: **Failed to build CUDA kernels for bias_act. Falling back to slow reference implementation.** 
Details:

Traceback (most recent call last):
  File "D:\python_learning\lafite\Lafite-main\torch_utils\ops\bias_act.py", line 41, in _init
    _plugin = custom_ops.get_plugin('bias_act_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])
  File "D:\python_learning\lafite\Lafite-main\torch_utils\custom_ops.py", line 57, in get_plugin
    raise RuntimeError(f'**Could not find MSVC/GCC/CLANG installation on this computer.** Check _find_compiler_bindir() in "{__file__}".')

RuntimeError: Could not find MSVC/GCC/CLANG installation on this computer. Check _find_compiler_bindir() in "D:\python_learning\lafite\Lafite-main\torch_utils\custom_ops.py".

  warnings.warn('Failed to build CUDA kernels for bias_act. Falling back to slow reference implementation. Details:\n\n' + traceback.format_exc())

Setting up PyTorch plugin "upfirdn2d_plugin"... Failed!
D:\python_learning\lafite\Lafite-main\torch_utils\ops\upfirdn2d.py:27: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:

Traceback (most recent call last):
  File "D:\python_learning\lafite\Lafite-main\torch_utils\ops\upfirdn2d.py", line 25, in _init
    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])
  File "D:\python_learning\lafite\Lafite-main\torch_utils\custom_ops.py", line 57, in get_plugin
    raise RuntimeError(f'Could not find MSVC/GCC/CLANG installation on this computer. Check _find_compiler_bindir() in "{__file__}".')

RuntimeError: **Could not find MSVC/GCC/CLANG installation on this computer.** Check _find_compiler_bindir() in "D:\python_learning\lafite\Lafite-main\torch_utils\custom_ops.py".

  warnings.warn('Failed to build CUDA kernels for **upfirdn2d**. Falling back to slow reference implementation. Details:\n\n' + traceback.format_exc())
Setting up PyTorch plugin "upfirdn2d_plugin"... Failed!
D:\python_learning\lafite\Lafite-main\torch_utils\ops\upfirdn2d.py:27: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:

Traceback (most recent call last):
  File "D:\python_learning\lafite\Lafite-main\torch_utils\ops\upfirdn2d.py", line 25, in _init
    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])
  File "D:\python_learning\lafite\Lafite-main\torch_utils\custom_ops.py", line 57, in get_plugin
    raise RuntimeError(f'Could not find MSVC/GCC/CLANG installation on this computer. Check _find_compiler_bindir() in "{__file__}".')
RuntimeError: Could not find MSVC/GCC/CLANG installation on this computer. Check _find_compiler_bindir() in "D:\python_learning\lafite\Lafite-main\torch_utils\custom_ops.py".

  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\n\n' + traceback.format_exc())
Setting up PyTorch plugin "**upfirdn2d_plugin**"... Failed!
D:\python_learning\lafite\Lafite-main\torch_utils\ops\upfirdn2d.py:27: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:

Traceback (most recent call last):
  File "D:\python_learning\lafite\Lafite-main\torch_utils\ops\upfirdn2d.py", line 25, in _init
    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])
  File "D:\python_learning\lafite\Lafite-main\torch_utils\custom_ops.py", line 57, in get_plugin
    raise RuntimeError(f'Could not find MSVC/GCC/CLANG installation on this computer. Check _find_compiler_bindir() in "{__file__}".')
RuntimeError: Could not find MSVC/GCC/CLANG installation on this computer. Check _find_compiler_bindir() in "D:\python_learning\lafite\Lafite-main\torch_utils\custom_ops.py".

  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\n\n' + traceback.format_exc())
Traceback (most recent call last):
  File "train.py", line 636, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "D:\app\Anaconda\envs\torch-py37\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "D:\app\Anaconda\envs\torch-py37\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "D:\app\Anaconda\envs\torch-py37\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\app\Anaconda\envs\torch-py37\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "D:\app\Anaconda\envs\torch-py37\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "train.py", line 629, in main
    subprocess_fn(rank=0, args=args, temp_dir=temp_dir)
  File "train.py", line 460, in subprocess_fn
    training_loop.training_loop(rank=rank, **args)
  File "D:\python_learning\lafite\Lafite-main\training\training_loop.py", line 181, in training_loop
    img = misc.print_module_summary(G, [z, c])
  File "D:\python_learning\lafite\Lafite-main\torch_utils\misc.py", line 205, in print_module_summary
    outputs = module(*inputs)
  File "D:\app\Anaconda\envs\torch-py37\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\python_learning\lafite\Lafite-main\training\networks.py", line 812, in forward
    img = self.synthesis(ws, fts=fts, styles=styles, return_styles=return_styles, **synthesis_kwargs)
  File "D:\app\Anaconda\envs\torch-py37\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\python_learning\lafite\Lafite-main\training\networks.py", line 759, in forward
    x, img, style_list, style_init_list, style_res_list = block(x, img, cur_ws, fts=fts, styles=cur_style, **block_kwargs)
  File "D:\app\Anaconda\envs\torch-py37\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\python_learning\lafite\Lafite-main\training\networks.py", line 667, in forward
    x, style_init, style_res  = self.conv1(x, next(w_iter), styles=next(s_iter), fts=fts, fused_modconv=fused_modconv, **layer_kwargs)
  File "D:\app\Anaconda\envs\torch-py37\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\python_learning\lafite\Lafite-main\training\networks.py", line 472, in forward
    padding=self.padding, resample_filter=self.resample_filter, flip_weight=flip_weight, fused_modconv=fused_modconv)
  File "D:\python_learning\lafite\Lafite-main\torch_utils\misc.py", line 94, in decorator
    return fn(*args, **kwargs)
  File "D:\python_learning\lafite\Lafite-main\training\networks.py", line 51, in modulated_conv2d
    dcoefs = (w.square().sum(dim=[2,3,4]) + 1e-8).rsqrt() # [NO]
RuntimeError: CUDA out of memory. Tried to allocate 144.00 MiB (GPU 0; 2.00 GiB total capacity; 618.39 MiB already allocated; 0 bytes free; 760.00 MiB reserved in total by PyTorch)`

**Comment by jexz11** [comment]
1:Setting up PyTorch plugin "bias_act_plugin"... Failed!
2:Could not find MSVC/GCC/CLANG installation on this computer. 
3:Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation.
4:CUDA out of memory. Tried to allocate 144.00 MiB (GPU 0; 2.00 GiB total capacity; 618.39 MiB already allocated; 0 bytes free; 760.00 MiB reserved in total by PyTorch)`

**Comment by jexz11** [comment]
What should I fix first?

**Comment by drboog** [comment]
Can you try the code on a GPU with larger memory? Or you can try to decrease the channel number and batch size.

**Comment by jexz11** [comment]
Okey,I will try it.

**Comment by jexz11** [comment]
Reducing the batch size still doesn't work, so let me think of other ways
`Tried to allocate 68.00 MiB (GPU 0; 2.00 GiB total capacity; 758.30 MiB already allocated; 0 bytes free; 830.00 MiB reserved in total by PyTorch)`

**Comment by jexz11** [comment]
![image](https://user-images.githubusercontent.com/76417800/158317242-a86bac4a-8faa-43ad-b0c7-69a155792fb2.png)
I started reporting errors when I found that the GPU utilization was not 100% when I ran the code

**Comment by jexz11** [comment]
RuntimeError: CUDA out of memory. Tried to allocate 68.00 MiB (GPU 0; 2.00 GiB total capacity; 758.30 MiB already allocated; 0 bytes free; 830.00 MiB reserved in total by PyTorch)

**Comment by jexz11** [comment]
2GB-758.30MB-830.00 MB<0 ?????

**Comment by jexz11** [comment]
**I just want to create my own Pokemon, why is it so hard ！！！！！！！**

**Comment by landian60** [comment]
> **I just want to create my own Pokemon, why is it so hard ！！！！！！！**

Guy you are so funny, I am a pokemon fan,too. It is a fantastic idea to create someone's unique pokemon, and what are your results?
