### ISSUE TITLE
resume pretrained model problem

### ISSUE THREAD

**Issue by CrisZhouh** [drboog/Lafite#36]
I trained CelebA datasets whose image size is 256 with pretrained FFHQ256model load. I tried <file> and ffhq256, but both failed with RuntimeError: The size of tensor a (512) must match the size of tensor b (256) at non-singleton dimension 0.
Strangely, I turn to ffhq512 and find it training successfully with terrible output.

**Comment by CrisZhouh** [comment]
I set f_dim=256 but still got wrong
the full debug information:
Traceback (most recent call last):
  File "/root/miniconda3/envs/zh/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/root/autodl-tmp/Lafite-main/train.py", line 460, in subprocess_fn
    training_loop.training_loop(rank=rank, **args)
  File "/root/autodl-tmp/Lafite-main/training/training_loop.py", line 174, in training_loop
    misc.copy_params_and_buffers(resume_data[name], module, require_all=False)
  File "/root/autodl-tmp/Lafite-main/torch_utils/misc.py", line 153, in copy_params_and_buffers
    tensor.copy_(src_tensors[name].detach()).requires_grad_(tensor.requires_grad)
RuntimeError: The size of tensor a (512) must match the size of tensor b (256) at non-singleton dimension 0
